DATA_PATH = "Data/problem_data.xlsx"

TIME_MACHINE_SETUP = 100
TIME_OPERATOR_FOR_EACH_WORK = 50
MAX_TIME_MACHINE = 50

COST_MACHINE_SETUP = 100
_DAILY_WORKING_HOURS = 10
DAILY_WORKING_MINUTES = _DAILY_WORKING_HOURS * 60
DAYS = 10
NUMBER_OF_MACHINES = 3
NUMBER_OF_PRODUCTS = 5
